#### 1. Python program to add two matrices.

In [5]:
x = [[1,2,3],
    [4,5,6],
    [7,8,9]]
y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range (len(x)):
    for j in range (len(x[0])):
        result[i][j] = x[i][j] + y[i][j]
        
for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


#### 2. Python program to multiply two matrices.

In [10]:
A = [[12,7,3],
    [4,5,6],
    [7,8,9]]
B = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]
for i in range(len(A)):
    
    for j in range(len(B[0])):
    
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


#### 3. Python program for Matrix product.

In [10]:
A = [[12,7,3],
    [4,5,6],
    [7,8,9]]
B = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]
for i in range(len(A)):
    
    for j in range(len(B[0])):
    
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


#### 4. Adding and Substracting Matrices in Python.

In [2]:
# Adding

import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [3]:
# Substrating

import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

print("Substraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Substraction of two matrix
[[-3 -3]
 [-3 -3]]


#### 5. Transepose a matrix in single line in Python.

In [11]:
m = [[1,2],[3,4],[5,6]]
for row in m :
    print(row)
rez = [[m[j][i] for j in range (len(m))] for i in range(len(m[0]))]
print("\n")
for row in rez:
    print(row)

[1, 2]
[3, 4]
[5, 6]


[1, 3, 5]
[2, 4, 6]


#### 6. Python | Matrix creation of n*n.

In [12]:
N = 4
print("The dimension : " + str(N))
res = [list(range(1 +N * i, 1 + N * (i + 1)))
      for i in range(N)]
print("The created matrix of N * N: " + str(res))

The dimension : 4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


#### 7. Python | Get kth Column of Matrix.

In [13]:
list = [[4,5,6], [8,1,10], [7,12,5]]

print("The original list is: " + str(list))
K = 2
res = [sub[K] for sub in list]
print("The Kth column of matrix is : " + str(res))

The original list is: [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
The Kth column of matrix is : [6, 10, 5]


#### 8. Python - Vertical Concatenation in Matrix.

In [14]:
list = [["Gfg", "good"], ["is", "for"], ["Best"]]
print("The original list : " + str(list))
res = []
N = 0
while N != len(list):
    temp = ''
    for idx in list:
        try: temp = temp + idx[N]
        except IndexError: pass
    res.append(temp)
    N = N + 1
res = [ele for ele in res if ele]
print("List after column Concatenation : " + str(res))

The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['GfgisBest', 'goodfor']


#### 9. Python program to check if a string is palindrome or not.

In [15]:
def isPalindrome(s):
    return s == s[::-1]
s = "malayalam"
ans = isPalindrome(s)
if ans:
    print("Yes")
else:
    print("No")

Yes


#### 10. Python program to check wheather the string is Symmetrical or Palindrome.

In [17]:
string = 'amaama'
half = int(len(string) / 2)

if len(string) % 2 == 0: 
    first_str = string[:half]
    second_str = string[half:]
else:
    first_str = string[:half]
    second_str = string[half+1:]
#symmetrical
if first_str == second_str:
    print(string, 'string is symmetrical')
else:
    print(string, 'string is not symmetrical')
    
#palindrome  
if first_str == second_str[::-1]:
    print(string, 'string is palindrome')
else:
    print(string, 'string is not palindrome')

amaama string is symmetrical
amaama string is palindrome
